[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pcb_defect"
version = "0.1.0"
description = "Utilities for PCB defect detection"
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "Matheus dos Santos Sounier", email = "matheus.sounier2024@gmail.com"}]
dependencies = []

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = ["src"]